model:
  model_name: "mistralai/Mistral-7B-Instruct-v0.2"
  model_type: "mistral"
  max_length: 2048
  use_flash_attention: true
  trust_remote_code: true

lora:
  r: 16
  lora_alpha: 32
  target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  max_steps: null
  optim: "paged_adamw_32bit"
  lr_scheduler_type: "cosine"
  fp16: true
  bf16: false
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  save_total_limit: 3
  evaluation_strategy: "steps"
  save_strategy: "steps"
  train_file: "data/processed/train.jsonl"
  validation_file: "data/processed/validation.jsonl"
  max_seq_length: 2048
  dataloader_pin_memory: false
  output_dir: "experiments/outputs"
  run_name: "mistral-finetune"
  report_to:
    - "tensorboard"

data:
  train_split: 0.9
  validation_split: 0.1
  test_split: 0.0
  random_seed: 42
  max_samples: null
  preprocessing_num_workers: 4