model:
  model_name: "microsoft/DialoGPT-medium"
  model_type: "gpt2"
  max_length: 512
  use_flash_attention: false
  trust_remote_code: false

lora:
  r: 8
  lora_alpha: 16
  target_modules:
    - "c_attn"
    - "c_proj"
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_steps: 50
  max_steps: null
  optim: "adamw_torch"
  lr_scheduler_type: "cosine"
  fp16: false
  bf16: false
  logging_steps: 10
  save_steps: 100
  eval_steps: 100
  save_total_limit: 2
  evaluation_strategy: "steps"
  save_strategy: "steps"
  train_file: "data/processed/train.jsonl"
  validation_file: "data/processed/validation.jsonl"
  max_seq_length: 512
  dataloader_pin_memory: false
  output_dir: "experiments/outputs"
  run_name: "test-run"
  report_to:
    - "tensorboard"

data:
  train_split: 0.8
  validation_split: 0.2
  test_split: 0.0
  random_seed: 42
  max_samples: 100
  preprocessing_num_workers: 2